### ISSUE TITLE
Incompatibility with super_diff -- `uninitialized constant RSpec::Expectations::ExpectationTarget`

### ISSUE THREAD

**Issue by Nakilon** [laserlemon/rspec-wait#35]
```console
$ tree -a
.
├── Gemfile
├── Gemfile.lock
├── .ruby-version
└── spec
    └── _spec.rb

$ cat .ruby-version 
2.7.8

$ cat  spec/_spec.rb 
require "super_diff/rspec"
require "rspec/wait"

$ cat Gemfile
source "https://rubygems.org"
gem "rspec-wait"
gem "super_diff"

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    attr_extras (7.1.0)
    diff-lcs (1.5.1)
    optimist (3.1.0)
    patience_diff (1.2.0)
      optimist (~> 3.0)
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.2)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.1)
    rspec-wait (0.0.10)
      rspec (>= 3.0)
    super_diff (0.9.0)
      attr_extras (>= 6.2.4)
      diff-lcs
      patience_diff

PLATFORMS
  ruby

DEPENDENCIES
  rspec-wait
  super_diff

BUNDLED WITH
   2.1.4
```
```console
$ bundle exec rspec

An error occurred while loading ./spec/_spec.rb.
Failure/Error: require "rspec/wait"

NameError:
  uninitialized constant RSpec::Expectations::ExpectationTarget
  Did you mean?  RSpec::Expectations::ExpectationHelper
# ./spec/_spec.rb:2:in `require'
# ./spec/_spec.rb:2:in `<top (required)>'
No examples found.


Finished in 0.00004 seconds (files took 0.11679 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by laserlemon** [comment]
Interesting! It appears you're on Ruby 2.7.8, but RSpec Wait requires Ruby 3.0 or later. I'm not sure how you were even able to install RSpec Wait when using that Ruby version. Can you reproduce the issue on Ruby 3.0? If you're able to reproduce the issue on a combination of Ruby and RSpec versions that are supported, please reopen this issue! RSpec Wait supports Ruby 3.0+ and RSpec 3.4+.

**Comment by Nakilon** [comment]
The issue does not happen if I reverse the order of `require`s. Why so?

Why doesn't rspec-wait support Ruby <3.0?
